apiRules: 
- exclude:
    uidRegex: AnonymousTypes
    type: Namespace
- exclude:
    uidRegex: DotNetForHtml5
    type: Namespace
- exclude:
    uidRegex: DotNetForHtml5.Core
    type: Namespace
- exclude:
    uidRegex: JSIL
    type: Namespace
- exclude:
    uidRegex: JSIL.Meta
    type: Namespace