### YamlMime:ManagedReference
items:
- uid: System.Net.Security
  commentId: N:System.Net.Security
  id: System.Net.Security
  children:
  - System.Net.Security.ProtectionLevel
  langs:
  - csharp
  - vb
  name: System.Net.Security
  nameWithType: System.Net.Security
  fullName: System.Net.Security
  type: Namespace
  assemblies:
  - CSHTML5.Runtime
references:
- uid: System.Net.Security.ProtectionLevel
  commentId: T:System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.Net.Security
  commentId: N:System.Net.Security
  name: System.Net.Security
  nameWithType: System.Net.Security
  fullName: System.Net.Security
