### YamlMime:ManagedReference
items:
- uid: Windows.ApplicationModel.Activation
  commentId: N:Windows.ApplicationModel.Activation
  id: Windows.ApplicationModel.Activation
  children:
  - Windows.ApplicationModel.Activation.LaunchActivatedEventArgs
  langs:
  - csharp
  - vb
  name: Windows.ApplicationModel.Activation
  nameWithType: Windows.ApplicationModel.Activation
  fullName: Windows.ApplicationModel.Activation
  type: Namespace
  assemblies:
  - OpenSilver.Runtime
references:
- uid: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs
  commentId: T:Windows.ApplicationModel.Activation.LaunchActivatedEventArgs
  parent: Windows.ApplicationModel.Activation
  name: LaunchActivatedEventArgs
  nameWithType: LaunchActivatedEventArgs
  fullName: Windows.ApplicationModel.Activation.LaunchActivatedEventArgs
- uid: Windows.ApplicationModel.Activation
  commentId: N:Windows.ApplicationModel.Activation
  name: Windows.ApplicationModel.Activation
  nameWithType: Windows.ApplicationModel.Activation
  fullName: Windows.ApplicationModel.Activation
