### YamlMime:ManagedReference
items:
- uid: CSHTML5.Internal.Attributes.SettingsAttribute
  commentId: T:CSHTML5.Internal.Attributes.SettingsAttribute
  id: SettingsAttribute
  parent: CSHTML5.Internal.Attributes
  children:
  - CSHTML5.Internal.Attributes.SettingsAttribute.#ctor
  - CSHTML5.Internal.Attributes.SettingsAttribute.GenerateJavaScriptDuringBuild
  langs:
  - csharp
  - vb
  name: SettingsAttribute
  nameWithType: SettingsAttribute
  fullName: CSHTML5.Internal.Attributes.SettingsAttribute
  type: Class
  source:
    id: SettingsAttribute
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\PublicAPI\Internal\Attributes\SettingsAttribute.cs
    startLine: 19
  assemblies:
  - OpenSilver
  namespace: CSHTML5.Internal.Attributes
  syntax:
    content: 'public sealed class SettingsAttribute : Attribute'
    content.vb: >-
      Public NotInheritable Class SettingsAttribute
          Inherits Attribute
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: CSHTML5.Internal.Attributes.SettingsAttribute.#ctor
  commentId: M:CSHTML5.Internal.Attributes.SettingsAttribute.#ctor
  id: '#ctor'
  parent: CSHTML5.Internal.Attributes.SettingsAttribute
  langs:
  - csharp
  - vb
  name: SettingsAttribute()
  nameWithType: SettingsAttribute.SettingsAttribute()
  fullName: CSHTML5.Internal.Attributes.SettingsAttribute.SettingsAttribute()
  type: Constructor
  source:
    id: .ctor
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\PublicAPI\Internal\Attributes\SettingsAttribute.cs
    startLine: 22
  assemblies:
  - OpenSilver
  namespace: CSHTML5.Internal.Attributes
  syntax:
    content: public SettingsAttribute()
    content.vb: Public Sub New
  overload: CSHTML5.Internal.Attributes.SettingsAttribute.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CSHTML5.Internal.Attributes.SettingsAttribute.GenerateJavaScriptDuringBuild
  commentId: P:CSHTML5.Internal.Attributes.SettingsAttribute.GenerateJavaScriptDuringBuild
  id: GenerateJavaScriptDuringBuild
  parent: CSHTML5.Internal.Attributes.SettingsAttribute
  langs:
  - csharp
  - vb
  name: GenerateJavaScriptDuringBuild
  nameWithType: SettingsAttribute.GenerateJavaScriptDuringBuild
  fullName: CSHTML5.Internal.Attributes.SettingsAttribute.GenerateJavaScriptDuringBuild
  type: Property
  source:
    id: GenerateJavaScriptDuringBuild
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\PublicAPI\Internal\Attributes\SettingsAttribute.cs
    startLine: 27
  assemblies:
  - OpenSilver
  namespace: CSHTML5.Internal.Attributes
  syntax:
    content: public bool GenerateJavaScriptDuringBuild { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property GenerateJavaScriptDuringBuild As Boolean
  overload: CSHTML5.Internal.Attributes.SettingsAttribute.GenerateJavaScriptDuringBuild*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CSHTML5.Internal.Attributes
  commentId: N:CSHTML5.Internal.Attributes
  name: CSHTML5.Internal.Attributes
  nameWithType: CSHTML5.Internal.Attributes
  fullName: CSHTML5.Internal.Attributes
- uid: System.Object
  commentId: T:System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  parent: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  definition: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  name: ToJavaScriptObject()
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject()
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject()
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  isExternal: true
  name: ToJavaScriptObject(Object)
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject(Object)
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  commentId: T:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  parent: ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
- uid: ToJavaScriptObjectExtender
  commentId: N:ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender
- uid: CSHTML5.Internal.Attributes.SettingsAttribute.#ctor*
  commentId: Overload:CSHTML5.Internal.Attributes.SettingsAttribute.#ctor
  name: SettingsAttribute
  nameWithType: SettingsAttribute.SettingsAttribute
  fullName: CSHTML5.Internal.Attributes.SettingsAttribute.SettingsAttribute
- uid: CSHTML5.Internal.Attributes.SettingsAttribute.GenerateJavaScriptDuringBuild*
  commentId: Overload:CSHTML5.Internal.Attributes.SettingsAttribute.GenerateJavaScriptDuringBuild
  name: GenerateJavaScriptDuringBuild
  nameWithType: SettingsAttribute.GenerateJavaScriptDuringBuild
  fullName: CSHTML5.Internal.Attributes.SettingsAttribute.GenerateJavaScriptDuringBuild
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
