### YamlMime:ManagedReference
items:
- uid: System.Runtime.InteropServices.Automation
  commentId: N:System.Runtime.InteropServices.Automation
  id: System.Runtime.InteropServices.Automation
  children:
  - System.Runtime.InteropServices.Automation.AutomationEvent
  - System.Runtime.InteropServices.Automation.AutomationEventArgs
  - System.Runtime.InteropServices.Automation.AutomationFactory
  langs:
  - csharp
  - vb
  name: System.Runtime.InteropServices.Automation
  nameWithType: System.Runtime.InteropServices.Automation
  fullName: System.Runtime.InteropServices.Automation
  type: Namespace
  assemblies:
  - OpenSilver
references:
- uid: System.Runtime.InteropServices.Automation.AutomationEvent
  commentId: T:System.Runtime.InteropServices.Automation.AutomationEvent
  parent: System.Runtime.InteropServices.Automation
  name: AutomationEvent
  nameWithType: AutomationEvent
  fullName: System.Runtime.InteropServices.Automation.AutomationEvent
- uid: System.Runtime.InteropServices.Automation.AutomationEventArgs
  commentId: T:System.Runtime.InteropServices.Automation.AutomationEventArgs
  name: AutomationEventArgs
  nameWithType: AutomationEventArgs
  fullName: System.Runtime.InteropServices.Automation.AutomationEventArgs
- uid: System.Runtime.InteropServices.Automation.AutomationFactory
  commentId: T:System.Runtime.InteropServices.Automation.AutomationFactory
  name: AutomationFactory
  nameWithType: AutomationFactory
  fullName: System.Runtime.InteropServices.Automation.AutomationFactory
- uid: System.Runtime.InteropServices.Automation
  commentId: N:System.Runtime.InteropServices.Automation
  name: System.Runtime.InteropServices.Automation
  nameWithType: System.Runtime.InteropServices.Automation
  fullName: System.Runtime.InteropServices.Automation
