### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Security
  commentId: N:System.ServiceModel.Security
  id: System.ServiceModel.Security
  children:
  - System.ServiceModel.Security.UserNamePasswordClientCredential
  langs:
  - csharp
  - vb
  name: System.ServiceModel.Security
  nameWithType: System.ServiceModel.Security
  fullName: System.ServiceModel.Security
  type: Namespace
  assemblies:
  - Runtime.OpenSilver
references:
- uid: System.ServiceModel.Security.UserNamePasswordClientCredential
  commentId: T:System.ServiceModel.Security.UserNamePasswordClientCredential
  name: UserNamePasswordClientCredential
  nameWithType: UserNamePasswordClientCredential
  fullName: System.ServiceModel.Security.UserNamePasswordClientCredential
