### YamlMime:ManagedReference
items:
- uid: System.Windows.Interop.Settings
  commentId: T:System.Windows.Interop.Settings
  id: Settings
  parent: System.Windows.Interop
  children:
  - System.Windows.Interop.Settings.#ctor
  - System.Windows.Interop.Settings.EnableAutoZoom
  - System.Windows.Interop.Settings.Windowless
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: Settings
  fullName: System.Windows.Interop.Settings
  type: Class
  source:
    id: Settings
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows.Interop\WORKINPROGRESS\Settings.cs
    startLine: 8
  assemblies:
  - OpenSilver
  namespace: System.Windows.Interop
  syntax:
    content: 'public sealed class Settings : object'
    content.vb: >-
      Public NotInheritable Class Settings
          Inherits Object
  inheritance:
  - System.Object
  extensionMethods:
  - System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: System.Windows.Interop.Settings.Windowless
  commentId: P:System.Windows.Interop.Settings.Windowless
  id: Windowless
  parent: System.Windows.Interop.Settings
  langs:
  - csharp
  - vb
  name: Windowless
  nameWithType: Settings.Windowless
  fullName: System.Windows.Interop.Settings.Windowless
  type: Property
  source:
    id: Windowless
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows.Interop\WORKINPROGRESS\Settings.cs
    startLine: 13
  assemblies:
  - OpenSilver
  namespace: System.Windows.Interop
  syntax:
    content: public bool Windowless { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property Windowless As Boolean
  overload: System.Windows.Interop.Settings.Windowless*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: System.Windows.Interop.Settings.EnableAutoZoom
  commentId: P:System.Windows.Interop.Settings.EnableAutoZoom
  id: EnableAutoZoom
  parent: System.Windows.Interop.Settings
  langs:
  - csharp
  - vb
  name: EnableAutoZoom
  nameWithType: Settings.EnableAutoZoom
  fullName: System.Windows.Interop.Settings.EnableAutoZoom
  type: Property
  source:
    id: EnableAutoZoom
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows.Interop\WORKINPROGRESS\Settings.cs
    startLine: 22
  assemblies:
  - OpenSilver
  namespace: System.Windows.Interop
  syntax:
    content: public bool EnableAutoZoom { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property EnableAutoZoom As Boolean
  overload: System.Windows.Interop.Settings.EnableAutoZoom*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Windows.Interop.Settings.#ctor
  commentId: M:System.Windows.Interop.Settings.#ctor
  id: '#ctor'
  parent: System.Windows.Interop.Settings
  langs:
  - csharp
  - vb
  name: Settings()
  nameWithType: Settings.Settings()
  fullName: System.Windows.Interop.Settings.Settings()
  type: Constructor
  source:
    id: .ctor
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows.Interop\WORKINPROGRESS\Settings.cs
    startLine: 36
  assemblies:
  - OpenSilver
  namespace: System.Windows.Interop
  syntax:
    content: public Settings()
    content.vb: Public Sub New
  overload: System.Windows.Interop.Settings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Windows.Interop
  commentId: N:System.Windows.Interop
  name: System.Windows.Interop
  nameWithType: System.Windows.Interop
  fullName: System.Windows.Interop
- uid: System.Object
  commentId: T:System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  parent: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  definition: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  name: ToJavaScriptObject()
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject()
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject()
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  isExternal: true
  name: ToJavaScriptObject(Object)
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject(Object)
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  commentId: T:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  parent: ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
- uid: ToJavaScriptObjectExtender
  commentId: N:ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender
- uid: System.Windows.Interop.Settings.Windowless*
  commentId: Overload:System.Windows.Interop.Settings.Windowless
  name: Windowless
  nameWithType: Settings.Windowless
  fullName: System.Windows.Interop.Settings.Windowless
- uid: System.Boolean
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Windows.Interop.Settings.EnableAutoZoom*
  commentId: Overload:System.Windows.Interop.Settings.EnableAutoZoom
  name: EnableAutoZoom
  nameWithType: Settings.EnableAutoZoom
  fullName: System.Windows.Interop.Settings.EnableAutoZoom
- uid: System.Windows.Interop.Settings.#ctor*
  commentId: Overload:System.Windows.Interop.Settings.#ctor
  name: Settings
  nameWithType: Settings.Settings
  fullName: System.Windows.Interop.Settings.Settings
