### YamlMime:ManagedReference
items:
- uid: System.ApplicationModel.Activation
  commentId: N:System.ApplicationModel.Activation
  id: System.ApplicationModel.Activation
  children:
  - System.ApplicationModel.Activation.LaunchActivatedEventArgs
  langs:
  - csharp
  - vb
  name: System.ApplicationModel.Activation
  nameWithType: System.ApplicationModel.Activation
  fullName: System.ApplicationModel.Activation
  type: Namespace
  assemblies:
  - OpenSilver
references:
- uid: System.ApplicationModel.Activation.LaunchActivatedEventArgs
  commentId: T:System.ApplicationModel.Activation.LaunchActivatedEventArgs
  parent: System.ApplicationModel.Activation
  name: LaunchActivatedEventArgs
  nameWithType: LaunchActivatedEventArgs
  fullName: System.ApplicationModel.Activation.LaunchActivatedEventArgs
- uid: System.ApplicationModel.Activation
  commentId: N:System.ApplicationModel.Activation
  name: System.ApplicationModel.Activation
  nameWithType: System.ApplicationModel.Activation
  fullName: System.ApplicationModel.Activation
