### YamlMime:ManagedReference
items:
- uid: Windows.UI.Xaml.IApplicationService
  commentId: T:Windows.UI.Xaml.IApplicationService
  id: IApplicationService
  parent: Windows.UI.Xaml
  children:
  - Windows.UI.Xaml.IApplicationService.StartService(Windows.UI.Xaml.ApplicationServiceContext)
  - Windows.UI.Xaml.IApplicationService.StopService
  langs:
  - csharp
  - vb
  name: IApplicationService
  nameWithType: IApplicationService
  fullName: Windows.UI.Xaml.IApplicationService
  type: Interface
  source:
    id: IApplicationService
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\WORKINPROGRESS\IApplicationService.cs
    startLine: 10
  assemblies:
  - Runtime.OpenSilver
  namespace: Windows.UI.Xaml
  syntax:
    content: public interface IApplicationService
    content.vb: Public Interface IApplicationService
  extensionMethods:
  - System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Windows.UI.Xaml.IApplicationService.StartService(Windows.UI.Xaml.ApplicationServiceContext)
  commentId: M:Windows.UI.Xaml.IApplicationService.StartService(Windows.UI.Xaml.ApplicationServiceContext)
  id: StartService(Windows.UI.Xaml.ApplicationServiceContext)
  parent: Windows.UI.Xaml.IApplicationService
  langs:
  - csharp
  - vb
  name: StartService(ApplicationServiceContext)
  nameWithType: IApplicationService.StartService(ApplicationServiceContext)
  fullName: Windows.UI.Xaml.IApplicationService.StartService(Windows.UI.Xaml.ApplicationServiceContext)
  type: Method
  source:
    id: StartService
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\WORKINPROGRESS\IApplicationService.cs
    startLine: 19
  assemblies:
  - Runtime.OpenSilver
  namespace: Windows.UI.Xaml
  syntax:
    content: void StartService(ApplicationServiceContext context)
    parameters:
    - id: context
      type: Windows.UI.Xaml.ApplicationServiceContext
    content.vb: Sub StartService(context As ApplicationServiceContext)
  overload: Windows.UI.Xaml.IApplicationService.StartService*
- uid: Windows.UI.Xaml.IApplicationService.StopService
  commentId: M:Windows.UI.Xaml.IApplicationService.StopService
  id: StopService
  parent: Windows.UI.Xaml.IApplicationService
  langs:
  - csharp
  - vb
  name: StopService()
  nameWithType: IApplicationService.StopService()
  fullName: Windows.UI.Xaml.IApplicationService.StopService()
  type: Method
  source:
    id: StopService
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\WORKINPROGRESS\IApplicationService.cs
    startLine: 23
  assemblies:
  - Runtime.OpenSilver
  namespace: Windows.UI.Xaml
  syntax:
    content: void StopService()
    content.vb: Sub StopService
  overload: Windows.UI.Xaml.IApplicationService.StopService*
references:
- uid: Windows.UI.Xaml
  commentId: N:Windows.UI.Xaml
  name: Windows.UI.Xaml
  nameWithType: Windows.UI.Xaml
  fullName: Windows.UI.Xaml
- uid: System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  parent: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  definition: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  name: ToJavaScriptObject()
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject()
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject()
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  isExternal: true
  name: ToJavaScriptObject(Object)
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject(Object)
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  commentId: T:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  parent: ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
- uid: ToJavaScriptObjectExtender
  commentId: N:ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender
- uid: Windows.UI.Xaml.IApplicationService.StartService*
  commentId: Overload:Windows.UI.Xaml.IApplicationService.StartService
  name: StartService
  nameWithType: IApplicationService.StartService
  fullName: Windows.UI.Xaml.IApplicationService.StartService
- uid: Windows.UI.Xaml.ApplicationServiceContext
  commentId: T:Windows.UI.Xaml.ApplicationServiceContext
  parent: Windows.UI.Xaml
  name: ApplicationServiceContext
  nameWithType: ApplicationServiceContext
  fullName: Windows.UI.Xaml.ApplicationServiceContext
- uid: Windows.UI.Xaml.IApplicationService.StopService*
  commentId: Overload:Windows.UI.Xaml.IApplicationService.StopService
  name: StopService
  nameWithType: IApplicationService.StopService
  fullName: Windows.UI.Xaml.IApplicationService.StopService
